theme: jekyll-theme-minimal
title: Thomas Picollin
description: Développeur PHP dans l'âme &#8226; Full Stack en devenir &#8226; Fervent Agiliste
show_downloads: false
lang: fr-FR
logo: /assets/img/logo.svg


